// <auto-generated />
using System;
using DemoShop.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoShop.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BSDemoShopContext))]
    [Migration("20230830085514_Create_SeedData")]
    partial class Create_SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Coupons", (string)null);
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuyerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(14)
                        .HasColumnType("decimal(14,0)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("MemberId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnTheMarket")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 8, 30, 8, 55, 14, 777, DateTimeKind.Utc).AddTicks(7000),
                            Description = "Product1 DESC.",
                            ImagePath = "https://picsum.photos/300/200/?random=1",
                            IsDelete = false,
                            IsOnTheMarket = true,
                            ProductName = "Product1"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 8, 30, 8, 55, 14, 777, DateTimeKind.Utc).AddTicks(7004),
                            Description = "Product222 DESC.",
                            ImagePath = "https://picsum.photos/300/200/?random=1",
                            IsDelete = false,
                            IsOnTheMarket = true,
                            ProductName = "Product222"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 8, 30, 8, 55, 14, 777, DateTimeKind.Utc).AddTicks(7006),
                            Description = "Product000 DESC.",
                            ImagePath = "https://picsum.photos/300/200/?random=1",
                            IsDelete = false,
                            IsOnTheMarket = true,
                            ProductName = "Product000"
                        });
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.ProductSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SpecificationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SpecificationId");

                    b.ToTable("ProductSpecifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 8, 30, 8, 55, 14, 777, DateTimeKind.Utc).AddTicks(7030),
                            IsDelete = false,
                            ProductId = 1,
                            SpecificationId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 8, 30, 8, 55, 14, 777, DateTimeKind.Utc).AddTicks(7033),
                            IsDelete = false,
                            ProductId = 1,
                            SpecificationId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 8, 30, 8, 55, 14, 777, DateTimeKind.Utc).AddTicks(7035),
                            IsDelete = false,
                            ProductId = 2,
                            SpecificationId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2023, 8, 30, 8, 55, 14, 777, DateTimeKind.Utc).AddTicks(7037),
                            IsDelete = false,
                            ProductId = 2,
                            SpecificationId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2023, 8, 30, 8, 55, 14, 777, DateTimeKind.Utc).AddTicks(7039),
                            IsDelete = false,
                            ProductId = 3,
                            SpecificationId = 5
                        });
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.Specification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Inventory")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecificationReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("SpecificationValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationReferenceId");

                    b.ToTable("Specifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inventory = 10,
                            IsDelete = false,
                            SKU = "Product1-XL",
                            SpecificationReferenceId = 1,
                            SpecificationValue = "XL",
                            UnitPrice = 10m
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inventory = 10,
                            IsDelete = false,
                            SKU = "Product1-S",
                            SpecificationReferenceId = 1,
                            SpecificationValue = "S",
                            UnitPrice = 11m
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inventory = 10,
                            IsDelete = false,
                            SKU = "Product222-Black",
                            SpecificationReferenceId = 3,
                            SpecificationValue = "黑色",
                            UnitPrice = 15m
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2023, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inventory = 15,
                            IsDelete = false,
                            SKU = "Product222-White",
                            SpecificationReferenceId = 3,
                            SpecificationValue = "白色",
                            UnitPrice = 13m
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2023, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Inventory = 100,
                            IsDelete = false,
                            SKU = "Product000",
                            SpecificationReferenceId = 2,
                            SpecificationValue = "單一規格",
                            UnitPrice = 1.5m
                        });
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.SpecificationReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("SpecificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SpecificationReferences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            SpecificationName = "尺寸"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            SpecificationName = "規格"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            SpecificationName = "顏色"
                        });
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.Order", b =>
                {
                    b.HasOne("DemoShop.ApplicationCore.Entities.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId");

                    b.HasOne("DemoShop.ApplicationCore.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.OrderItem", b =>
                {
                    b.HasOne("DemoShop.ApplicationCore.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.ProductSpecification", b =>
                {
                    b.HasOne("DemoShop.ApplicationCore.Entities.Product", "Product")
                        .WithMany("ProductSpecifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemoShop.ApplicationCore.Entities.Specification", "Specification")
                        .WithMany("ProductSpecifications")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Specification");
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.Specification", b =>
                {
                    b.HasOne("DemoShop.ApplicationCore.Entities.SpecificationReference", "SpecificationReference")
                        .WithMany("Specifications")
                        .HasForeignKey("SpecificationReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecificationReference");
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.Product", b =>
                {
                    b.Navigation("ProductSpecifications");
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.Specification", b =>
                {
                    b.Navigation("ProductSpecifications");
                });

            modelBuilder.Entity("DemoShop.ApplicationCore.Entities.SpecificationReference", b =>
                {
                    b.Navigation("Specifications");
                });
#pragma warning restore 612, 618
        }
    }
}
