// <auto-generated />
using System;
using BS.DemoShop.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BS.DemoShop.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BSDemoShopContext))]
    [Migration("20220912070954_EntitiesModelBuilder")]
    partial class EntitiesModelBuilder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BS.DemoShop.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTimeOffset(new DateTime(2022, 9, 12, 7, 9, 53, 719, DateTimeKind.Unspecified).AddTicks(2990), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "預設分類1",
                            Sort = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTimeOffset(new DateTime(2022, 9, 12, 7, 9, 53, 720, DateTimeKind.Unspecified).AddTicks(3120), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "預設分類2",
                            Sort = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTimeOffset(new DateTime(2022, 9, 12, 7, 9, 53, 720, DateTimeKind.Unspecified).AddTicks(3200), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "預設分類3",
                            Sort = 2
                        });
                });

            modelBuilder.Entity("BS.DemoShop.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnTheMarket")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedTime = new DateTime(2022, 9, 12, 7, 9, 53, 728, DateTimeKind.Utc).AddTicks(1770),
                            ImgPath = "https://picsum.photos/300/200/?random=1",
                            IsOnTheMarket = true,
                            Name = "種子商品1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedTime = new DateTime(2022, 9, 12, 7, 9, 53, 728, DateTimeKind.Utc).AddTicks(2620),
                            ImgPath = "https://picsum.photos/300/200/?random=2",
                            IsOnTheMarket = false,
                            Name = "種子商品2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedTime = new DateTime(2022, 9, 12, 7, 9, 53, 728, DateTimeKind.Utc).AddTicks(2620),
                            ImgPath = "https://picsum.photos/300/200/?random=3",
                            IsOnTheMarket = true,
                            Name = "種子商品3"
                        });
                });

            modelBuilder.Entity("BS.DemoShop.Core.Entities.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Inventory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2022, 9, 12, 7, 9, 53, 730, DateTimeKind.Utc).AddTicks(5350),
                            Inventory = 100,
                            Name = "種子規格1",
                            ProductId = 1,
                            UnitPrice = 100m
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2022, 9, 12, 7, 9, 53, 730, DateTimeKind.Utc).AddTicks(5830),
                            Inventory = 10,
                            Name = "種子規格2",
                            ProductId = 1,
                            UnitPrice = 100m
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2022, 9, 12, 7, 9, 53, 730, DateTimeKind.Utc).AddTicks(5840),
                            Inventory = 8,
                            Name = "種子規格3",
                            ProductId = 1,
                            UnitPrice = 100m
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2022, 9, 12, 7, 9, 53, 730, DateTimeKind.Utc).AddTicks(5840),
                            Inventory = 18,
                            Name = "種子規格4",
                            ProductId = 2,
                            UnitPrice = 100m
                        },
                        new
                        {
                            Id = 5,
                            CreatedTime = new DateTime(2022, 9, 12, 7, 9, 53, 730, DateTimeKind.Utc).AddTicks(5840),
                            Inventory = 0,
                            Name = "種子規格4",
                            ProductId = 3,
                            UnitPrice = 100m
                        },
                        new
                        {
                            Id = 6,
                            CreatedTime = new DateTime(2022, 9, 12, 7, 9, 53, 730, DateTimeKind.Utc).AddTicks(5850),
                            Inventory = 120,
                            Name = "種子規格4",
                            ProductId = 3,
                            UnitPrice = 100m
                        },
                        new
                        {
                            Id = 7,
                            CreatedTime = new DateTime(2022, 9, 12, 7, 9, 53, 730, DateTimeKind.Utc).AddTicks(5850),
                            Inventory = 20,
                            Name = "種子規格4",
                            ProductId = 3,
                            UnitPrice = 100m
                        });
                });

            modelBuilder.Entity("BS.DemoShop.Core.Entities.Product", b =>
                {
                    b.HasOne("BS.DemoShop.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BS.DemoShop.Core.Entities.ProductDetail", b =>
                {
                    b.HasOne("BS.DemoShop.Core.Entities.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BS.DemoShop.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BS.DemoShop.Core.Entities.Product", b =>
                {
                    b.Navigation("ProductDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
